{% set version = "1.0.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tidyxl
  version: {{ version|replace("-", "_") }}

source:
  fn: tidyxl_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/tidyxl_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tidyxl/tidyxl_{{ version }}.tar.gz
  sha256: f0770f94f607dfb85df24bfa5d20428322af99a49b3515a2145b293220a3b0d9

build:
  merge_build_host: true  # [win]
  number: 1
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_cxx') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp
    - r-piton
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp
    - r-piton

test:
  commands:
    - $R -e "library('tidyxl')"           # [not win]
    - "\"%R%\" -e \"library('tidyxl')\""  # [win]

about:
  home: https://github.com/nacnudus/tidyxl
  license: GPL-3
  summary: Imports non-tabular from Excel files into R.  Exposes cell content, position and formatting in a tidy structure for further manipulation. Tokenizes Excel
    formulas.  Supports '.xlsx' and '.xlsm' via the embedded 'RapidXML' C++ library <http://rapidxml.sourceforge.net>.  Does not support '.xlsb' or '.xls'.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
