travis:
  secure:
    BINSTAR_TOKEN: iWCvZIGUqc+Tk03R2Hjj5rhv/DiaxTrZmy6W3+7SYgnE4Cb0NX92TwMadWncsDiMT1uf70zQmeQn1DUtyLknDZWETKX/pE9fVV6gYRUpZYz10iNWvxnPIJ3cAKlnSWiDTDv9JLb//tpiK+KOMI8zEub44TlK/Qn8kgogUK1+hseL+ccFJmhoSGwu1/jEBZNYHqyGZpHLxMJOjDOQQ8NedsyaKIA2iMLjjHmfiEioyFaf/i5WyaQizOPsJXwB36S75GDAoOpyzXuaxV8ODZLSxNuTM0wxw9ST1zlyuk+T6uaO7e4d3eqXu7lOzf7SNsUum7/6JnEOMhV+2qJiwI6NMKfdySfTr17objlQdAOmbVfcofJvGBIr46Xe7MnQ3nN3FlJ4B5nTh+uMmhcPadv1iZUYhPGit0pXay387WZYtxgz/Bn8VWZf0ZuU/wx5mfQ7HZI8VxvMr1tcRQc9Pws5N3QIyGtFPUewXqJZyhYGc2rSCFI2Y4GHVXQah1X4CzwP+2urhfrFHRrPayvAdNAED/AREnEDed8bxslHYsv9XR3B/xpjA5BQuUe+qiLT70WI2+JDQhlDxZ6jBOasvduAGxCjtdmDRxtsFS5ddKiJvrkiHhSurCEbIMHmDg035DDCtGY2cTY7I4/w7KMCI2PCIrHwOmOJngAXUoJJxD36Zc4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
